import {
  LayoutGrid,
  ShoppingBag,
  ChefHat,
  Utensils,
  Boxes,
  ReceiptText,
  BarChart3,
  Settings,
  Users,
  CalendarDays,
} from 'lucide-react';
import { AppItem } from '../types/launcher.types';

export const APPS: AppItem[] = [
  {
    id: 'salon',
    name: 'Salón y Mesas',
    subtitle: 'Mapa interactivo y estados',
    icon: LayoutGrid,
    gradient: 'from-emerald-400 to-teal-600',
    badge: 'En vivo',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    category: 'operacion',
  },
  {
    id: 'reservations',
    name: 'Reservas de Mesas',
    subtitle: 'Agenda, confirmación y asignación',
    icon: CalendarDays,
    gradient: 'from-pink-500 to-rose-600',
    badge: 'Fase 6',
    badgeColor: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
    category: 'operacion',
  },
  {
    id: 'pos',
    name: 'Punto de Venta',
    subtitle: 'Comandero, caja y modificadores',
    icon: ShoppingBag,
    gradient: 'from-amber-400 to-orange-600',
    category: 'operacion',
  },
  {
    id: 'kds',
    name: 'Cocina KDS',
    subtitle: 'Pantalla de preparación en tiempo real',
    icon: ChefHat,
    gradient: 'from-rose-500 to-red-600',
    badge: 'KDS',
    badgeColor: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
    category: 'operacion',
  },
  {
    id: 'catalog',
    name: 'Menú y Catálogo',
    subtitle: 'Productos, categorías y variantes',
    icon: Utensils,
    gradient: 'from-blue-400 to-indigo-600',
    category: 'gestion',
  },
  {
    id: 'inventory',
    name: 'Inventario & Recetas',
    subtitle: 'Descuento automático de insumos',
    icon: Boxes,
    gradient: 'from-violet-400 to-purple-600',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    category: 'gestion',
  },
  {
    id: 'shifts',
    name: 'Caja & Facturación',
    subtitle: 'Arqueos, pagos y tickets',
    icon: ReceiptText,
    gradient: 'from-cyan-400 to-blue-600',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    category: 'gestion',
  },
  {
    id: 'reports',
    name: 'Reportes & Métricas',
    subtitle: 'Ventas, mermas y tiempos',
    icon: BarChart3,
    gradient: 'from-fuchsia-400 to-pink-600',
    badge: 'BI En vivo',
    badgeColor: 'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/30',
    category: 'gestion',
  },
  {
    id: 'users',
    name: 'Empleados & Roles',
    subtitle: 'Gestión de personal y PINs',
    icon: Users,
    gradient: 'from-amber-500 to-rose-600',
    category: 'gestion',
  },
  {
    id: 'settings',
    name: 'Ajustes y Marca',
    subtitle: 'Logo, datos fiscales y colores',
    icon: Settings,
    gradient: 'from-slate-500 to-slate-700',
    category: 'config',
  },
];
