import {
  LayoutGrid,
  ShoppingBag,
  ChefHat,
  Utensils,
  Boxes,
  ReceiptText,
  BarChart3,
  Settings,
  Users,
  CalendarDays,
} from 'lucide-react';
import { AppItem } from '../types/launcher.types';

export const APPS: AppItem[] = [
  {
    id: 'salon',
    name: 'Salón y Mesas',
    subtitle: 'Mapa interactivo y estados',
    icon: LayoutGrid,
    icon3d: '/icons/modules/dining-table.webp',
    gradient: 'from-emerald-400 to-teal-600',
    badgeColor: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30',
    category: 'operacion',
  },
  {
    id: 'reservations',
    name: 'Reservas de Mesas',
    subtitle: 'Agenda, confirmación y asignación',
    icon: CalendarDays,
    icon3d: '/icons/modules/calendar.webp',
    gradient: 'from-pink-500 to-rose-600',
    badgeColor: 'bg-pink-500/15 text-pink-700 dark:text-pink-300 border-pink-500/30',
    category: 'operacion',
  },
  {
    id: 'pos',
    name: 'Punto de Venta',
    subtitle: 'Comandero, caja y modificadores',
    icon: ShoppingBag,
    icon3d: '/icons/modules/cash-register.webp',
    gradient: 'from-amber-400 to-orange-600',
    category: 'operacion',
  },
  {
    id: 'kds',
    name: 'Cocina KDS',
    subtitle: 'Pantalla de preparación en tiempo real',
    icon: ChefHat,
    icon3d: '/icons/modules/chef.webp',
    gradient: 'from-rose-500 to-red-600',
    badgeColor: 'bg-rose-500/15 text-rose-700 dark:text-rose-300 border-rose-500/30',
    category: 'operacion',
  },
  {
    id: 'catalog',
    name: 'Menú y Catálogo',
    subtitle: 'Productos, categorías y variantes',
    icon: Utensils,
    icon3d: '/icons/modules/takeout-menu.webp',
    gradient: 'from-blue-400 to-indigo-600',
    category: 'gestion',
  },
  {
    id: 'inventory',
    name: 'Inventario y Recetas',
    subtitle: 'Stock, insumos y fichas técnicas',
    icon: Boxes,
    icon3d: '/icons/modules/open-shipping-box.webp',
    gradient: 'from-indigo-500 to-violet-600',
    category: 'gestion',
  },
  {
    id: 'shifts',
    name: 'Caja y Turnos',
    subtitle: 'Aperturas, arqueos y movimientos',
    icon: ReceiptText,
    icon3d: '/icons/modules/safe.webp',
    gradient: 'from-emerald-500 to-green-700',
    category: 'operacion',
  },
  {
    id: 'reports',
    name: 'Reportes y Métricas',
    subtitle: 'Ventas, gráficos y estadísticas',
    icon: BarChart3,
    icon3d: '/icons/modules/bar-chart.webp',
    gradient: 'from-teal-400 to-cyan-600',
    category: 'gestion',
  },
  {
    id: 'users',
    name: 'Usuarios y Roles',
    subtitle: 'Gestión de personal y accesos',
    icon: Users,
    icon3d: '/icons/modules/waiter.webp',
    gradient: 'from-purple-500 to-fuchsia-600',
    category: 'config',
  },
  {
    id: 'settings',
    name: 'Configuración',
    subtitle: 'Empresa, impuestos e impresoras',
    icon: Settings,
    icon3d: '/icons/modules/settings.webp',
    gradient: 'from-slate-600 to-slate-800',
    category: 'config',
  },
];
